homepage/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^/en$', views.index_en, name='index_en'),
]

zealotlabs_django/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('homepage.urls', namespace='homepage')),
]

homepage/views.py
from django.shortcuts import render, render_to_response
from django.template import RequestContext

def index(request):
    return render_to_response('homepage/index_cn.html', {}, context_instance=RequestContext(request))

def index_en(request):
    return render_to_response('homepage/index_en.html', {}, context_instance=RequestContext(request))

homepage/templates/homepage/index_cn.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ZealotLabs | 解决方案</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Custom CSS -->
    <link href="{% static "homepage/css/stylish-portfolio.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <!--<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">ZealotLabs 解决方案</span> 
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#top">ZealotLabs</a>
                    </li>
                    <li>
                        <a href="#about">关于我们</a>
                    </li>
                    <li>
                        <a href="#services">服务</a>
                    </li>
                    <li>
                        <a href="#team">团队</a>
                    </li>
                    <!-- Add team portfolio later.
                    <li>
                        <a href="#portfolio">Portfolio</a>
                    </li>
                    -->
                    <li>
                        <a href="#contact">联系我们</a>
                    </li>
                    <li>
                        <a href="{% url 'homepage:index_en' %}">English</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>ZealotLabs</h1>
            <h3>We transform your idea into product.</h3>
            <p class="lead">从这里, 硅谷.</p>
            <br>
            <a href="#about" class="btn btn-circle page-scroll">
                <i class="fa fa-angle-double-down animated"></i>
            </a>
        </div>
    </header>

    <!-- About -->
    <section id="about" class="about bg-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>关于我们</h2>
                    <p class="lead">
                        我们是一群身在加州硅谷的工程师. 我们能快速的把您的想法转换成网页,移动产品.
                    </p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Services -->
    <!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
    <section id="services" class="services">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-10 col-lg-offset-1">
                    <h2>服务</h2>
                    <hr class="small">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="service-icon fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-desktop fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong>网页产品</strong>
                                </h4>
                                <p>前端UI, 后端服务和数据管理. </p>
                                <!--a href="#" class="btn btn-light">Learn More</a-->
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="service-icon fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-tablet fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong>移动app</strong>
                                </h4>
                                <p>iOS / Andriod app + 后端服务.</p>
                                <!--a href="#" class="btn btn-light">Learn More</a-->
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="service-icon fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-shield fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong>产品模块</strong>
                                </h4>
                                <p>支付, 搜索, 机器学习, 验证, API设计</p>
                                <!--a href="#" class="btn btn-light">Learn More</a-->
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="service-icon fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-plug fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong>平台整合</strong>
                                </h4>
                                <p>云存储, 缓存服务器, 产品部署</p>
                                <!--a href="#" class="btn btn-light">Learn More</a-->
                            </div>
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Portfolio -->
    <section id="team" class="team bg-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h2>团队</h2>
                    <hr class="small">
                    <div class="row">
                        <p class="lead">
                            我们的团队成员来自硅谷顶尖IT公司, 比如Google, Facebook, Microsoft, Amazon, LinkedIn, Box.
                        </p>
                    </div>
                    <!-- /.row (nested) -->
                    <!--a href="#" class="btn btn-dark">Meet Us</a-->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Call to Action -->
    <aside id="contact" class="call-to-action backbackgray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>让我们聊聊能为您做什么.</h3>
                    <a href="mailto:info@zealotlabs.com" class="btn btn-lg btn-dark">Email我们!</a>
                </div>
            </div>
        </div>
    </aside>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>ZealotLabs</strong>
                    </h4>
                    <ul class="list-unstyled">
                        <!--li><i class="fa fa-phone fa-fw"></i> (123) 456-7890</li-->
                        <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:info@zealotlabs.com">info@zealotlabs.com</a>
                        </li>
                    </ul>
                    <h5>帕罗奥图, 加州, 美国</h5>
                    <br>
                    <!--ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul-->
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; ZealotLabs 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <!--<script src="js/jquery.js"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!--<script src="js/bootstrap.min.js"></script>-->

    <!-- Custom Theme JavaScript -->
    <script>

    // jQuery to collapse the navbar on scroll
    $(window).scroll(function() {
        if ($(".navbar").offset().top > 50) {
            $(".navbar-fixed-top").addClass("top-nav-collapse");
        } else {
            $(".navbar-fixed-top").removeClass("top-nav-collapse");
        }
    });

    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    </script>
</body>
</html>

homepage/templates/homepage/index_en.html
<!DOCTYPE html>
<html lang="en">

<head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>ZealotLabs | Solutions</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">

    <!-- Custom CSS -->
    <link href="{% static "homepage/css/stylish-portfolio.css" %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <!--<link href="font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">-->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">

    <link href="http://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,700,300italic,400italic,700italic" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand page-scroll" href="#page-top">
                    <i class="fa fa-play-circle"></i>  <span class="light">ZealotLabs Solutions</span> 
                </a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <li class="sidebar-brand">
                        <a href="#top">ZealotLabs</a>
                    </li>
                    <li>
                        <a href="#about">About</a>
                    </li>
                    <li>
                        <a href="#services">Services</a>
                    </li>
                    <li>
                        <a href="#team">Team</a>
                    </li>
                    <!-- Add team portfolio later.
                    <li>
                        <a href="#portfolio">Portfolio</a>
                    </li>
                    -->
                    <li>
                        <a href="#contact">Contact</a>
                    </li>
                    <li>
                        <a href="{% url 'homepage:index' %}">中文版</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Header -->
    <header id="top" class="header">
        <div class="text-vertical-center">
            <h1>ZealotLabs</h1>
            <h3>We Transform Your Idea to Product.</h3>
            <p class="lead">Here at Silicon valley.</p>
            <br>
            <a href="#about" class="btn btn-circle page-scroll">
                <i class="fa fa-angle-double-down animated"></i>
            </a>
        </div>
    </header>

    <!-- About -->
    <section id="about" class="about bg-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2>Implement your cool idea with minimal cost!</h2>
                    <p class="lead">
                        We are tech enthusiasts at silicon valley, beautiful California. We can turn your ideas to web/mobile product in a timely manner.
                    </p>
                </div>
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Services -->
    <!-- The circle icons use Font Awesome's stacked icon classes. For more information, visit http://fontawesome.io/examples/ -->
    <section id="services" class="services">
        <div class="container">
            <div class="row text-center">
                <div class="col-lg-10 col-lg-offset-1">
                    <h2>Our Services</h2>
                    <hr class="small">
                    <div class="row">
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="service-icon fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-desktop fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong>Web App</strong>
                                </h4>
                                <p>Frontend, backend and database. </p>
                                <!--a href="#" class="btn btn-light">Learn More</a-->
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="service-icon fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-tablet fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong>Mobile App</strong>
                                </h4>
                                <p>iOS / Andriod app with backend services.</p>
                                <!--a href="#" class="btn btn-light">Learn More</a-->
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="service-icon fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-shield fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong>Feature Enhancement</strong>
                                </h4>
                                <p>Payment, Search, Machine learning, Authentication, Restful-API.</p>
                                <!--a href="#" class="btn btn-light">Learn More</a-->
                            </div>
                        </div>
                        <div class="col-md-3 col-sm-6">
                            <div class="service-item">
                                <span class="service-icon fa-stack fa-4x">
                                    <i class="fa fa-circle fa-stack-2x"></i>
                                    <i class="fa fa-plug fa-stack-1x text-primary"></i>
                                </span>
                                <h4>
                                    <strong>Platform Intigration</strong>
                                </h4>
                                <p>Cloud storage Caching Server deploy. Amazon AWS.</p>
                                <!--a href="#" class="btn btn-light">Learn More</a-->
                            </div>
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Portfolio -->
    <section id="team" class="team bg-gray">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h2>Our Team</h2>
                    <hr class="small">
                    <div class="row">
                        <p class="lead">
                            Our team members have work experience in Google, Facebook, Microsoft, Amazon, LinkedIn, Box, and many other top tech companies in silicon valley.
                        </p>
                    </div>
                    <!-- /.row (nested) -->
                    <!--a href="#" class="btn btn-dark">Meet Us</a-->
                </div>
                <!-- /.col-lg-10 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.container -->
    </section>

    <!-- Call to Action -->
    <aside id="contact" class="call-to-action backbackgray">
        <div class="container">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h3>Let's talk about what we can do for you.</h3>
                    <a href="mailto:info@zealotlabs.com" class="btn btn-lg btn-dark">Email Us!</a>
                </div>
            </div>
        </div>
    </aside>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-lg-offset-1 text-center">
                    <h4><strong>ZealotLabs</strong>
                    </h4>
                    <ul class="list-unstyled">
                        <!--li><i class="fa fa-phone fa-fw"></i> (123) 456-7890</li-->
                        <li><i class="fa fa-envelope-o fa-fw"></i>  <a href="mailto:info@zealotlabs.com">info@zealotlabs.com</a>
                        </li>
                    </ul>
                    <h5>Palo Alto, CA, USA</h5>
                    <br>
                    <!--ul class="list-inline">
                        <li>
                            <a href="#"><i class="fa fa-facebook fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-twitter fa-fw fa-3x"></i></a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-dribbble fa-fw fa-3x"></i></a>
                        </li>
                    </ul-->
                    <hr class="small">
                    <p class="text-muted">Copyright &copy; ZealotLabs 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <!--<script src="js/jquery.js"></script>-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

    <!-- Bootstrap Core JavaScript -->

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
    <!--<script src="js/bootstrap.min.js"></script>-->

    <!-- Custom Theme JavaScript -->
    <script>

    // jQuery to collapse the navbar on scroll
    $(window).scroll(function() {
        if ($(".navbar").offset().top > 50) {
            $(".navbar-fixed-top").addClass("top-nav-collapse");
        } else {
            $(".navbar-fixed-top").removeClass("top-nav-collapse");
        }
    });

    // Scrolls to the selected menu item on the page
    $(function() {
        $('a[href*=#]:not([href=#])').click(function() {
            if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') || location.hostname == this.hostname) {

                var target = $(this.hash);
                target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                if (target.length) {
                    $('html,body').animate({
                        scrollTop: target.offset().top
                    }, 1000);
                    return false;
                }
            }
        });
    });
    </script>
</body>
</html>